from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$',views.index,name='Index'),
    url(r'^Register/$',views.register,name='Register'),
    url(r'^Home/$',views.home,name='Home'),
    url(r'^CompleteRegistration/$',views.registerUser,name='RegisterUser'),
    url(r'^Login/$',views.login,name='Login'),
    url(r'^Logout/$',views.logout,name='Logout'),
    url(r'^UpdateProfile/$',views.updateprofile,name='UpdateProfile'),
    url(r'^ResetPassword/$',views.resetpassword,name='ResetPassword'),
    url(r'^EditContact/$',views.editcontact,name='EditContact'),
    url(r'^EditAddress/$',views.editaddress,name='EditAddress'),
    url(r'^Search/$',views.searchperson,name='SearchPerson'),
    url(r'^ProcessRequest/$',views.processrequest,name='ProcessRequest'),
    url(r'^RequestSent/$',views.requestsent,name='RequestSent'),
    url(r'^ViewUser/$',views.viewuser,name='ViewUser'),
    url(r'^RequestRecieved/$',views.requestrecieved,name='RequestRecieved'),
    url(r'^AcceptRequest/$',views.acceptrequest,name='AcceptRequest'),
    url(r'^RejectRequest/$',views.rejectrequest,name='RejectRequest'),
    url(r'^AdminLogin/$',views.adminlogin,name='AdminLogin'),
    url(r'^CheckLogin/$',views.checklogin,name='CheckLogin'),
    url(r'^AdminHome/$',views.adminhome,name='AdminHome'),
    url(r'^AdminLogout/$',views.adminlogout,name='AdminLogout'),
    url(r'^BloodBank/$',views.bloodbank,name='BloodBank'),
    url(r'^ProcessBankRequest/$',views.processbankrequest,name='ProcessBankRequest'),
    url(r'^BankRequest/$',views.bankrequest,name='BankRequest'),
    url(r'^AcceptBankRequest/$',views.acceptbankrequest,name='AcceptBankRequest'),
    url(r'^RejectBankRequest/$',views.rejectbankrequest,name='RejectBankRequest'),
    url(r'^ViewAdminUser/$',views.viewadminuser,name='ViewAdminUser'),
    url(r'^AlterStock/$',views.alterstock,name='AlterStock'),
    url(r'^ForgotPassword/$',views.forgotpassword,name='ForgotPassword'),
    url(r'^ChangePassword/$',views.changepassword,name='ChangePassword'),
]
