# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('bldgrp', models.CharField(max_length=20)),
                ('profile', models.CharField(max_length=200)),
            ],
        ),
    ]
