# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-22 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(upload_to=''),
        ),
    ]
