# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-23 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20181222_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=40)),
                ('reciever', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=40)),
            ],
        ),
    ]
