# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-24 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='bldgrp',
            field=models.CharField(default='', max_length=20),
        ),
    ]
