# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-25 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_remove_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default='1996-11-13'),
        ),
    ]
